### ISSUE TITLE
How to export onnx file from model(OccDepth.py)?

### ISSUE THREAD

**Issue by xyzhou-dev** [megvii-research/OccDepth#7]
[commit a8456da4e70a5fde48cec4d9ca44625c827bac79](https://github.com/megvii-research/OccDepth/commit/a8456da4e70a5fde48cec4d9ca44625c827bac79)

purpose:
- to run inference process in onnxruntime directly(without gpu dependence)
- It is convenient to port this model to run on [x]pu in the future

---
1. run export onnx enabled cmd
`python occdepth/models/OccDepth.py +export_onnx=True`
![image](https://user-images.githubusercontent.com/130032157/230910315-2acb4171-fd9e-4dc3-b7af-a33a0df551db.png)
and i found that it's depend on a data.pkl as input. try to run step 2.
2. export data.pkl via generate_output.py(with some changes) then copy to project dir
![image](https://user-images.githubusercontent.com/130032157/230910983-fef95208-7123-4bd8-80d2-d8f11480fe96.png)
`python occdepth/scripts/generate_output.py`
3. run run export onnx enabled cmd again; howerver get a TypeError as follow showing:
`
TypeError: forward() missing 1 required positional argument: 
`
![image](https://user-images.githubusercontent.com/130032157/230912119-a41cd9ad-112e-46ff-b82b-f9da76f20afd.png)
**Which step is wrong?** please correct me.

---
appreciate for your help in advance.
It would be great to provide an onnx(can be used) file. ^_^

**Comment by rhmiao** [comment]
1. export data.pkl for NYUv2 is added in [194f106](https://github.com/megvii-research/OccDepth/commit/194f1062413c886a492b530e2f99cdf6cd84b3ba)
you can run:
```
cd occdepth
source env_NYU.sh
python occdepth/data/NYU/nyu_dm.py  
```
or
```
cd occdepth
source env_semanticKITTI.sh
python occdepth/data/semantic_kitti/kitti_dm.py
```
then `data.pkl` will be generated in `occdepth` dir

2. `TypeError: forward() missing 1 required positional argument: ` is fixed in: [f321c48](https://github.com/megvii-research/OccDepth/commit/f321c486f27a961a9e3c5d7ea95f26d566957e23)
then you can run:
```
python occdepth/models/OccDepth.py +export_onnx=True
```
the `.onnx` file is saved in `outputs` dir

@xyzhou-dev

**Comment by xyzhou-dev** [comment]
thank for your reply, can export onnx now.

**Comment by xyzhou-dev** [comment]
I forgot use kitti model to test export onnx.  today, i have a try and got an issue as following:
``` text
python occdepth/models/OccDepth.py +export_onnx=True
INFO: Use cascade cls: True
INFO: Use occluded cls: False
Loading base model tf_efficientnet_b3_ns...Done.
Removing last two layers (global_pool & classifier).
Building Encoder-Decoder model..Done.
INFO: return_up_feats set to : 1.
INFO: Selected 2d->3d transformation method: flosp_depth
INFO: Use step decay loss: False
Traceback (most recent call last):
  File "occdepth/models/OccDepth.py", line 677, in test_func
    res = model(fake_data)
  File "/home/***/miniconda3/envs/occdepth-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "occdepth/models/OccDepth.py", line 372, in forward
    x3ds, depth_pred = self._forward_2d_to_3d(batch, x_rgb, img, bs, vox_origin)
  File "occdepth/models/OccDepth.py", line 314, in _forward_2d_to_3d
    grids = batch["grids"]
KeyError: 'grids'
```
How to fill the grids field of the batch or some paramter need to set ?
``` python
if self.infer_mode:
     grids = batch["grids"]
     scaled_pixel_size = batch["scaled_pixel_size"]
     input_kwargs = {
        "img_feat": img_feat,
        "grids": grids,
        "scaled_pixel_size": scaled_pixel_size,
}
```

**Comment by rhmiao** [comment]
you can fill it as following:
```python
        if infer_mode:
            if config.dataset == "kitti":
                fake_grid = torch.rand(
                    1,
                    config.full_scene_size[0] // config.project_scale,
                    config.full_scene_size[1] // config.project_scale,
                    config.full_scene_size[2] // config.project_scale,
                    3,
                )
            elif config.dataset == "NYU":
                fake_grid = torch.rand(
                    1,
                    config.full_scene_size[0] // config.project_scale,
                    config.full_scene_size[2] // config.project_scale,
                    config.full_scene_size[1] // config.project_scale,
                    3,
                )
            fake_data["grids"] = [fake_grid for i in range(num_view)]
            fake_scaled_pixel_size = torch.rand(num_view, 1)
            fake_data["scaled_pixel_size"] = fake_scaled_pixel_size
```

**Comment by xyzhou-dev** [comment]
``` diff
diff --git a/occdepth/models/OccDepth.py b/occdepth/models/OccDepth.py
index 800b221..80319c7 100644
--- a/occdepth/models/OccDepth.py
+++ b/occdepth/models/OccDepth.py
@@ -670,6 +670,30 @@ if __name__ == "__main__":
             infer_mode=infer_mode,
             config=config,
         )
+
+        if infer_mode:
+            num_view = 2 if model.multi_view_mode else 1
+            print("num_view", num_view)
+            if config.dataset == "kitti":
+                fake_grid = torch.rand(
+                    1,
+                    config.full_scene_size[0] // config.project_scale,
+                    config.full_scene_size[1] // config.project_scale,
+                    config.full_scene_size[2] // config.project_scale,
+                    3,
+                )
+            elif config.dataset == "NYU":
+                fake_grid = torch.rand(
+                    1,
+                    config.full_scene_size[0] // config.project_scale,
+                    config.full_scene_size[2] // config.project_scale,
+                    config.full_scene_size[1] // config.project_scale,
+                    3,
+                )
+            fake_data["grids"] = [fake_grid for i in range(num_view)]
+            fake_scaled_pixel_size = torch.rand(num_view, 1)
+            fake_data["scaled_pixel_size"] = fake_scaled_pixel_size
+
         # 传入需要两个数据 一个是 正常传入网络的结构，一个是网络
         # 如果网络加载到cuda中，传入的数据也需要.cuda()
         model.eval()
```
i have a try with above patch and still encountered other errors as following:
``` text
eval: python occdepth/models/OccDepth.py +export_onnx=True
INFO: Use cascade cls: True
INFO: Use occluded cls: False
Loading base model tf_efficientnet_b3_ns...Done.
Removing last two layers (global_pool & classifier).
Building Encoder-Decoder model..Done.
INFO: return_up_feats set to : 1.
INFO: Selected 2d->3d transformation method: flosp_depth
INFO: Use step decay loss: False
num_view 2
Traceback (most recent call last):
  File "occdepth/models/OccDepth.py", line 701, in test_func
    res = model(fake_data)
  File "/home/***/miniconda3/envs/occdepth-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "occdepth/models/OccDepth.py", line 372, in forward
    x3ds, depth_pred = self._forward_2d_to_3d(batch, x_rgb, img, bs, vox_origin)
  File "occdepth/models/OccDepth.py", line 330, in _forward_2d_to_3d
    x3ds_depth, depth_pred = self.flosp_depth(
  File "/home/***/miniconda3/envs/occdepth-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/***/OccDepth/occdepth/models/flosp_depth/flosp_depth.py", line 537, in forward
    depth_feature = self._forward_depth_net(
  File "/home/***/OccDepth/occdepth/models/flosp_depth/flosp_depth.py", line 424, in _forward_depth_net
    return self.depth_net[0](
  File "/home/***/miniconda3/envs/occdepth-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/***/OccDepth/occdepth/models/flosp_depth/flosp_depth.py", line 253, in forward
    x = self.se(x, x_se)
  File "/home/***/miniconda3/envs/occdepth-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/***/OccDepth/occdepth/models/flosp_depth/flosp_depth.py", line 198, in forward
    return x * self.gate(x_se)
RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by xyzhou-dev** [comment]
fate_data相关的问题(trans_2d_to_3d: "flosp")：
---
采用主线kitti_dm.py生成的data.pkl去作为fake_data，再去生成的onnx模型，inputs/outputs为：
``` text
INFO:root:input tensor with shape:[2, 2, 3, 370, 1220]
INFO:root:input tensor with shape:[2, 262144, 1, 2]
INFO:root:input tensor with shape:[2, 262144, 1, 2]
INFO:root:input tensor with shape:[2, 262144, 1]
INFO:root:input tensor with shape:[2, 262144, 1]
INFO:root:output tensor with shape:[2, 20, 256, 256, 32]
```
将KittiDataModule初始化参数与generator_output.py对齐后(见下面的diff)，再重新去生成data.pkl->export onnx，其inputs/outputs为：
``` text
INFO:root:input tensor with shape:[1, 2, 3, 370, 1220]
INFO:root:input tensor with shape:[2, 262144, 1, 2]
INFO:root:input tensor with shape:[2, 262144, 1]
INFO:root:output tensor with shape:[1, 20, 256, 256, 32]
```
**是否采用generator_output.py的KittiDataModule参数更符合预期？**

---
``` diff
diff --git a/occdepth/data/semantic_kitti/kitti_dm.py b/occdepth/data/semantic_kitti/kitti_dm.py
index d6177db..9dd6b39 100644
--- a/occdepth/data/semantic_kitti/kitti_dm.py
+++ b/occdepth/data/semantic_kitti/kitti_dm.py
@@ -158,9 +158,8 @@ if __name__ == "__main__":
             root=config.data_root,
             preprocess_root=config.data_preprocess_root,
             frustum_size=config.frustum_size,
-            project_scale=config.project_scale,
-            batch_size=2,
-            num_workers=0,
+            batch_size=int(config.batch_size_per_gpu),
+            num_workers=int(config.num_workers_per_gpu * config.n_gpus),
             pattern_id=config.pattern_id,
             multi_view_mode=config.multi_view_mode,
             use_stereo_depth_gt=config.use_stereo_depth_gt,
```
